### ISSUE TITLE
Use the new Workflow component

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/dx.symfony.com#8]
When the new Workflow component is ready (see https://github.com/symfony/symfony/pull/11882), use it to control the state of the issues. Our transitions are very straightforward: `new` -> `discussing` -> `wip` -> `finished`

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because we no longer use this application.

**Comment by fabpot** [comment]
Does it mean that we can remove it entirely?

**Comment by HeahDude** [comment]
please don't I'm working on a project on top of if, we can remove it later, unless it harms!
